acipher: add missed header
LONG_MAX is defined in limits.h header

  optee_examples/acipher/host/main.c:46:22: error:
  use of undeclared identifier 'LONG_MAX'

Signed-off-by: SeongOok CHOI <kakapapa2@gmail.com>
Reviewed-by: Jerome Forissier <jerome@forissier.org>