pluging: add missing of dependency syslog on teec
Adds missing dependency of plugins/syslog example on libteec header files
that are brought in by libteec. The issue was reported by compiler with
the below build error message:

/tmp/optee/optee_examples/plugins/syslog/syslog_plugin.c:8:10: fatal error: tee_plugin_method.h: No such file or directory
    8 | #include <tee_plugin_method.h>
      |          ^~~~~~~~~~~~~~~~~~~~~

Acked-by: Jerome Forissier <jerome.forissier@linaro.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>