Secure_storage: fix size type into uint32_t
Type size_t is a deprecated type used in GPD TEE Client API v1.0, since v1.1
size arguments are typed uint32_t. Secure storage examples was not updated.

This error was reported with NXP LSDK (flexbbuild system with
gcc-aach64-linux-gnu <aarch64-linux-gnu-gcc (Ubuntu/Linaro 7.3.0-27ubuntu1~18.04) 7.3.0) with trace:

secure_storage_ta.c:203:6: error: passing argument 4 of ‘TEE_ReadObjectData’ from incompatible pointer type [-Werror=incompatible-pointer-types]
&read_bytes);

Signed-off-by: Zhenchuan Chai <zcchai@iotex.io>
Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>